name: Run Script

on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Execute Script
      run: |
        chmod +x now.sh
        ./now.sh
